version: '3'
services:
  db:
    image: postgres:14-alpine
    command: >
      -c ssl=on
      -c ssl_cert_file=/var/lib/postgresql/postgres.crt
      -c ssl_key_file=/var/lib/postgresql/postgres.key
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
       - ./persist/db:/var/lib/postgresql/data
       - ./ca/postgres.crt:/var/lib/postgresql/postgres.crt
       - ./ca/postgres.key:/var/lib/postgresql/postgres.key