# docker-compose.yml
version: '3.1'
services:
  db:
    image: postgres:14.10-alpine3.19
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
       - ./data:/var/lib/postgresql/data